version: '3.8'

services:
  sandbox:
    image: sandbox:0.1.2
    restart: always
    security_opt:
    - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    environment:
      API_KEY: aioai-sandbox
      MAX_REQUESTS: 100
      MAX_WORKERS: 30
      WORKER_TIMEOUT: 60
    ports:
      - "8194:8194"
    command: uvicorn main:app --host 0.0.0.0 --port 8194
    #command: tail -f /dev/null
    privileged: true